name: Simplified release
on:
  push:
    tags:
      - '*'
permissions:
  contents: 'write'
  packages: 'write'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b'
        with:
          fetch-depth: 0
      - uses: 'actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2'
        with:
          go-version: '1.19'
      - uses: 'goreleaser/goreleaser-action@v3.2.0'
        with:
          args: 'release --rm-dist'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'